version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
  db:
    image: 'mysql'
    environment:
      - MYSQL_PASS=password
    volumes:
      - db-data:/test

volumes:
  db-data:
